# Where things are
source              : ./site
destination         : ./_site
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass

kramdown:
  hard_wrap: true
