# Where things are
source              : .
destination         : ./_site
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass

kramdown:
  hard_wrap: true

title: "tout le monde fait semblant"
description: "fictions courtes sur le quotidien et le vide de l'existence. introspectif et désabusé. je crois. c'est pas grave parce que tout le monde fait semblant."
url: "https://toutlemondefaitsemblant.fr"

plugins:
  - jekyll-sitemap
