# Where things are
source              : .
destination         : ./_site
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
  style: compressed
collections:
  textes:
    output: true
    sort_by: year
    permalink: /:collection/:slug

kramdown:
  hard_wrap: true

title: "tout le monde fait semblant"
description: "fictions courtes sur le quotidien et le vide de l'existence. introspectif et désabusé. je crois. c'est pas grave, tout le monde fait semblant."
url: "https://toutlemondefaitsemblant.fr"
author: tlmfs

plugins:
  - jekyll-feed
  - jekyll-sitemap

# optional feed config
feed:
  collections:
    - textes
  excerpt_only: true  # true to only display preview
